#!/usr/bin/env python3

import sqlite3, readline, sys, re, datetime
from ui import *
from libjtt import *

PROG_NAME = 'job-time-tracker'
VERSION = '0.1.0'
DB_NAME = sys.path[0] + '/data.db'

con = sqlite3.connect(DB_NAME)
cur = con.cursor()

create_tables(cur)
con.commit()

while True:
    # Пытаемся получить значение выбранного периода времени
    current_period = (cur.execute('SELECT selected_period FROM config').fetchone())

    if current_period is None:
        # Если нет записанного значения - получаем текущий месяц в виде ГГГГ-ММ
        current_period = (cur.execute("SELECT date()").fetchone())[0][:7]
        # и записываем его в БД
        cur.execute('INSERT INTO config VALUES(?)', (current_period, ))
        con.commit()
    else:
        # Если получилось получить значение из БД, приводим его к виду ГГГГ-ММ
        current_period = current_period[0]


    # Пытаемся получить строки данных за выбранный период времени
    period_data = get_period_data(cur, current_period)    


    # Пытаемся получить конфигурацию текущего выбранного периода времени


    period_params = get_period_params(cur, current_period)
    
    
    clear()
    header(' '.join((PROG_NAME, VERSION, ':', current_period)))
    print_as_table(
            [[key for key in period_params.keys()]] + 
                [[str(value) for value in period_params.values()]], ' ') if period_params else print('')
    line()
    
    print_as_table(period_data, ' ') if period_data else print('Нет данных за указанный период...')

    menu(('add', 'quit', 'next month', 'previous month'), 2)

    




    action = input('>> ').lower().strip()

    if action not in 'pnqa': help('not_impl', 1)
    elif action== 'q': break
    elif action == 'a':
        print('Пока необходимо вводить данные в формате ГГГГ-ММ-ДД Д.Ч Н.Ч')
        line = input().split(' ')
        cur.execute('insert into period_data values(?, ?, ?)', line)
    

    elif action in 'pn':
        cp = datetime.date.fromisoformat(current_period + '-10')
        td = datetime.timedelta(days=31)

        if action == 'p':
            td = datetime.timedelta(days=-31)

        cp += td
        cur.execute('UPDATE config SET selected_period = ?', (cp.strftime("%Y-%m"), ))
    
        con.commit()



con.close()




#  #  # Enable SIG handlers and configure readline
#  #  readline.set_completer_delims('\n,')

#  #  # Get user data and diary from db
#  #  user_data = get_user_data_by_id(cur, user_id)


    #  #  diary = get_data_for_diary(cur, current_date.strftime('%Y-%m-%d'), user_id)
    #  #  kcal_norm = libsd.get_calories_norm(user_data)
    #  #  kcal_per_day = '%.1f' % sum([line[2] for line in diary])
#  while(True):
    #  if current_date_was_changed:
        #  data_from_db = cur.execute('SELECT * FROM data where date >= ? and date <= ?', (start_date, end_date)).fetchall()
        #  current_date_was_changed = False




#  #  ui.screen(
        #  #  user_data['name'] + ': ' + libsd.HEADERS[screen_name] + ' ' + current_date.strftime('%Y-%m-%d'),
        #  #  lambda:
        #  #  ui.print_as_table( [('норма калорий'.upper(), '', kcal_norm)] + diary + [('всего'.upper(), '', kcal_per_day)],  ' ' ) if diary else print(libsd.EMPTY_BODY[screen_name] + f' {current_date}'),
        #  #  libsd.MENUS_ENTRIES[screen_name], 2)

    #  #  # Enable tab-completion
    #  #  readline.parse_and_bind('tab: complete')
    #  #  readline.set_completer(c.Completer([food[0] for food in food_list]).complete)

            #  else: helps.help('ua', 1)

    #  elif action not in 'lpnqht' and len(action) > 2:
        #  new_entry = { 'date': current_date, 'user': user_id, }

        #  for el in [ i.strip() for i in action.split(',') ]:

            #  data = libsd.parse_line(el)

            #  new_entry['title'] = data[0]
            #  new_entry['value'] = data[1] if data[1] is not None else input(f"количество для '{new_entry['title'][:1].upper() + new_entry['title'][1:]}': ")

            #  if is_in_db(cur, new_entry['title']) is None:
                #  print(f'Похоже, что такого блюда как \'{new_entry["title"]}\' нет в базе\nТребуется ввод дополнительной инофрмации')

                #  # Добавляем новый продукт в БД
                #  d = get_data({'kcal': 'калорийность',
                          #  'p': 'содержание белков',
                          #  'f': 'содержание жиров',
                          #  'c': 'содержание углеводов'}, 1)

                #  d['title'] = new_entry['title']
                #  add_new_food(cur, d)
                #  con.commit()
                #  db_was_changed = True

            #  # Добавляем запись в дневник
            #  add_in_diary(cur, new_entry)
            #  con.commit()

    #  else: helps.help('ua', 1)

